default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: worklog_development

test:
  <<: *default
  database: worklog_test

production:
  primary:
    <<: *default
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: loggy_lou-db
    port: 5432

  cable:
    <<: *default
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: loggy_lou-db
    port: 5432

  queue:
      <<: *default
      database: <%= ENV['POSTGRES_DB'] %>
      username: <%= ENV['POSTGRES_USER'] %>
      password: <%= ENV['POSTGRES_PASSWORD'] %>
      host: loggy_lou-db
      port: 5432

  cache:
      <<: *default
      database: <%= ENV['POSTGRES_DB'] %>
      username: <%= ENV['POSTGRES_USER'] %>
      password: <%= ENV['POSTGRES_PASSWORD'] %>
      host: loggy_lou-db
      port: 5432