# Name of your application. Used to uniquely configure containers.
service: loggy_lou

# Name of the container image.
image: izraphail/loggy_lou

# Deploy to these servers.
servers:
  web:
    - 164.92.228.202


# Credentials for your image host.
registry:
  username: izraphail
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    DB_HOST: loggy_lou-db
    DB_NAME: loggy_lou
    DB_USER: loggy_lou
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

ssh:
  user: root

# Use a persistent storage volume.
#
volumes:
  - "/root/data/loggy_lou/storage:/rails/storage"

accessories:
  db:
    image: postgres:16-alpine
    host: 164.92.228.202
    port: 5432
    env:
      clear:
        POSTGRES_DB: loggy_lou
        POSTGRES_USER: loggy_lou
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

