# Name of your application. Used to uniquely configure containers.
service: loggy_lou

# Name of the container image.
image: izraphail/loggy_lou

servers:
  web:
    - 164.92.228.202

registry:
  username: izraphail
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    DB_HOST: loggy_lou-db 
    POSTGRES_DB: loggy_lou
    POSTGRES_USER: loggy_lou
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

ssh:
  user: root

volumes:
  - "/root/data/loggy_lou/storage:/rails/storage"

accessories:
  db:
    image: postgres:16-alpine
    host: 164.92.228.202
    
    env:
      clear:
        POSTGRES_DB: loggy_lou
        POSTGRES_USER: loggy_lou
      secret:
        - POSTGRES_PASSWORD
    directories:
      - "/root/data/loggy_lou/db:/var/lib/postgresql/data"