# Name of your application. Used to uniquely configure containers.
service: loggy_lou

# Name of the container image.
image: izraphail/loggy_lou

servers:
  web:
    - 0.0.0.0

proxy:
  ssl: true
  host: example.com

registry:
  username: izraphail
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear: {}
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PASSWORD

ssh:
  user: root

volumes:
  - "/root/data/loggy_lou/storage:/rails/storage"

accessories:
  db:
    image: postgres:16-alpine
    host: 0.0.0.0
    
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
    directories:
      - "/root/data/loggy_lou/db:/var/lib/postgresql/data"